var commonSymbols = [
  {
    "type": "二元运算符 Binary operations",
    "list": [
      {"text": "+", "latex": "+"},
      {"text": "-", "latex": "-"},
      {"text": "×", "latex": "\\times"},
      {"text": "÷", "latex": "\\div"},
      {"text": "±", "latex": "\\pm"},
      {"text": "∓", "latex": "\\mp"},
      {"text": "◁", "latex": "\\triangleleft"},
      {"text": "▷", "latex": "\\triangleright"},
      {"text": "·", "latex": "\\cdot"},
      {"text": "\\", "latex": "\\setminus"},
      {"text": "★", "latex": "\\star"},
      {"text": "*", "latex": "\\ast"},
      {"text": "∪", "latex": "\\cup"},
      {"text": "∩", "latex": "\\cap"},
      {"text": "⊔", "latex": "\\sqcup"},
      {"text": "⊓", "latex": "\\sqcap"},
      {"text": "∨", "latex": "\\vee"},
      {"text": "∧", "latex": "\\wedge"},
      {"text": "○", "latex": "\\circ"},
      {"text": "●", "latex": "\\bullet"},
      {"text": "⊕", "latex": "\\oplus"},
      {"text": "⊖", "latex": "\\ominus"},
      {"text": "⊙", "latex": "\\odot"},
      {"text": "⊘", "latex": "\\oslash"},
      {"text": "⊗", "latex": "\\otimes"},
      {"text": "○", "latex": "\\bigcirc"},
      {"text": "◇", "latex": "\\diamond"},
      {"text": "⊎", "latex": "\\uplus"},
      {"text": "△", "latex": "\\bigtriangleup"},
      {"text": "▽", "latex": "\\bigtriangledown"},
      {"text": "◁", "latex": "\\lhd"},
      {"text": "▷", "latex": "\\rhd"},
      {"text": "≤", "latex": "\\leqq"},
      {"text": "≥", "latex": "\\geqq"},
      {"text": "Ⅱ", "latex": "\\amalg"},
      {"text": "∼", "latex": "\\sim"},
      {"text": "†", "latex": "\\dagger"},
      {"text": "‡", "latex": "\\ddagger"}
    ]
  },
  {
    "type": "二元关系符 Binary relations",
    "list": [
      {"text": "<", "latex": "<"},
      {"text": ">", "latex": ">"},
      {"text": "=", "latex": "="},
      {"text": "≤", "latex": "\\le"},
      {"text": "≥", "latex": "\\ge"},
      {"text": "≡", "latex": "\\equiv"},
      {"text": "≪", "latex": "\\ll"},
      {"text": "≫", "latex": "\\gg"},
      {"text": "≓", "latex": "\\doteq"},
      {"text": "⊂", "latex": "\\subset"},
      {"text": "⊃", "latex": "\\supset"},
      {"text": "∼", "latex": "\\sim"},
      {"text": "⊏", "latex": "\\sqsubset"},
      {"text": "⊐", "latex": "\\sqsupset"},
      {"text": "≃", "latex": "\\simeq"},
      {"text": "⊂", "latex": "\\subsetneq"},
      {"text": "⊃", "latex": "\\supsetneq"},
      {"text": "⊆", "latex": "\\subseteq"},
      {"text": "⊇", "latex": "\\supseteq"},
      {"text": "⊑", "latex": "\\sqsubseteq"},
      {"text": "⊒", "latex": "\\sqsupseteq"},
      {"text": "≈", "latex": "\\approx"},
      {"text": "⋈", "latex": "\\bowtie"},
      {"text": "⋈", "latex": "\\Join"},
      {"text": "∝", "latex": "\\propto"},
      {"text": "∈", "latex": "\\in"},
      {"text": "∋", "latex": "\\ni"},
      {"text": "⊢", "latex": "\\vdash"},
      {"text": "⊣", "latex": "\\dashv"},
      {"text": "⊩", "latex": "\\models"},
      {"text": "|", "latex": "\\mid"},
      {"text": "∥", "latex": "\\parallel"},
      {"text": "⊥", "latex": "\\perp"},
      {"text": "⌒", "latex": "\\frown"},
      {"text": "⌢", "latex": "\\smile"},
      {"text": "≍", "latex": "\\asymp"},
      {"text": ":", "latex": ":"},
      {"text": "∉", "latex": "\\notin"},
      {"text": "≠", "latex": "\\neq"}
    ]
  },
  {
    "type": "箭头符号 Arrows",
    "list": [
      {"text": "←", "latex": "\\leftarrow"},
      {"text": "→", "latex": "\\rightarrow"},
      {"text": "⇐", "latex": "\\Leftarrow"},
      {"text": "⇒", "latex": "\\Rightarrow"},
      {"text": "↑", "latex": "\\uparrow"},
      {"text": "↓", "latex": "\\downarrow"},
      {"text": "⇕", "latex": "\\updownarrow"},
      {"text": "↔", "latex": "\\leftrightarrow"},
      {"text": "⇑", "latex": "\\Uparrow"},
      {"text": "⇓", "latex": "\\Downarrow"},
      {"text": "⇕", "latex": "\\Updownarrow"},
      {"text": "⇔", "latex": "\\Leftrightarrow"},
      {"text": "⇐", "latex": "\\Longleftarrow"},
      {"text": "⇒", "latex": "\\Longrightarrow"},
      {"text": "⇔", "latex": "\\Longleftrightarrow"},
      {"text": "⟹", "latex": "\\implies"},
      {"text": "⟺", "latex": "\\iff"},
      {"text": "↦", "latex": "\\mapsto"},
      {"text": "⇀", "latex": "\\rightharpoonup"},
      {"text": "⇁", "latex": "\\rightharpoondown"},
      {"text": "↼", "latex": "\\leftharpoonup"},
      {"text": "↽", "latex": "\\leftharpoondown"},
      {"text": "↩", "latex": "\\hookleftarrow"},
      {"text": "↪", "latex": "\\hookrightarrow"},
      {"text": "↬", "latex": "\\looparrowleft"},
      {"text": "↫", "latex": "\\looparrowright"},
      {"text": "⇝", "latex": "\\leadsto"},
      {"text": "⊣", "latex": "\\dashleftarrow"},
      {"text": "⊢", "latex": "\\dashrightarrow"}
    ]
  },
  {
    "type": "其他符号 Others",
    "list": [
      {"text": "∴", "latex": "\\therefore"},
      {"text": "∵", "latex": "\\because"},
      {"text": "…", "latex": "\\dots"},
      {"text": "⋯", "latex": "\\cdots"},
      {"text": ":", "latex": "\\colon"},
      {"text": "⋱", "latex": "\\ddots"},
      {"text": "∀", "latex": "\\forall"},
      {"text": "∃", "latex": "\\exists"},
      {"text": "∄", "latex": "\\nexists"},
      {"text": "⌋", "latex": "\\lfloor"},
      {"text": "⌈", "latex": "\\lceil"},
      {"text": "⌉", "latex": "\\rceil"},
      {"text": "⌊", "latex": "\\rfloor"},
      {"text": "/", "latex": "/"},
      {"text": "ø", "latex": "\\emptyset"},
      {"text": "∞", "latex": "\\infty"},
      {"text": "∇", "latex": "\\nabla"},
      {"text": "△", "latex": "\\triangle"},
      {"text": "□", "latex": "\\square"},
      {"text": "◇", "latex": "\\diamondsuit"},
      {"text": "⊥", "latex": "\\bot"},
      {"text": "⊤", "latex": "\\top"},
      {"text": "∠", "latex": "\\angle"},
      {"text": "∡", "latex": "\\measuredangle"},
      {"text": "∢", "latex": "\\sphericalangle"},
      {"text": "√", "latex": "\\surd"},
      {"text": "◇", "latex": "\\lozenge"},
      {"text": "♡", "latex": "\\heartsuit"},
      {"text": "♣", "latex": "\\clubsuit"},
      {"text": "♠", "latex": "\\spadesuit"},
      {"text": "♭", "latex": "\\flat"},
      {"text": "♯", "latex": "\\sharp"},
      {"text": "♮", "latex": "\\natural"}
    ]
  }
];